### ISSUE TITLE
Make links in Comments sections clickable like a hyperlink.

### ISSUE THREAD

**Issue by IkelAtomig** [TeamPiped/Piped#1244]

**Comment by ManeraKai** [comment]
We had a problem in LibRedirect where if you right click and `open link` on a text youtube link, it will bypass it the same way it'll do when pressing the `Watch on YouTube` button as the `origin` is from a piped instance.
A fix for that would be to do it like invidious. They remove the domain name from youtube urls and make it as such:
![image](https://user-images.githubusercontent.com/40805353/181770022-446652c3-53a0-47d2-9303-0d011c1d698d.png)

**Comment by EdwardLangdon** [comment]
I would like this issue to be reopened. I think the URL should be made like Invidious and all YouTube links in comments should be YouTube but the actual link is Piped.

This request is made because it escapes Libredirect's redirect function and also users might find this frustating both Libredirect and Piped cuz going to YT instead of Piped isn't liked by many.

**Comment by IkelAtomig** [comment]
Any updates ?

**Comment by Bnyro** [comment]
No idea to be honest, it's already been almost 2 years ago 🤷

**Comment by Bnyro** [comment]
Due to https://github.com/TeamPiped/Piped/pull/1421 I think.

**Comment by Bnyro** [comment]
This should already be working properly looking at https://github.com/TeamPiped/Piped/blob/master/src/utils/HtmlUtils.js. Any example video where it doesn't? @opusforlife2
