### ISSUE TITLE
[Request] Rating bar (likes/dislikes) on the bottom of every YouTube thumbnail.

### ISSUE THREAD

**Issue by f-x1-1** [TeamPiped/Piped#1571]
### Describe the feature

Thumbnails for YouTube is an extension that Displays a rating bar (likes/dislikes) on the bottom of every YouTube thumbnail. 

### Why would this be useful to add?

It would be useful to determine whether the video you’re about to watch is worth watching by looking at the rating bar on the thumbnail. 

### Concept(s)

[Thumbnails for YouTube](https://addons.mozilla.org/en-GB/firefox/addon/youtube-thumbnail-rating-bar/)

 

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by thecashewtrader** [comment]
I looked into the code for this, but first a suggestion: I think it would be better to show the actual numbers of likes and dislikes, so that users can see both `like:dislike` ratio and total interactions (likes+dislikes), a bit like this:
![image](https://user-images.githubusercontent.com/81344401/197347051-9837a3a5-df30-4e48-b494-5cf4c28aaead.png)

As for implementation, currently the `VideoItem` component (the one that's used when showing Video lists) uses `/streams/:videoId` (Specifically `relatedStreams`) or `/trending/:videoId` and so on. These endpoints do not return likes and dislikes, only the `/streams/:videoId` endpoint (The main video, not related videos) does.

Therefore, this would require API changes.

**Comment by Bnyro** [comment]
That data is not even returned in the API response of YouTube search, so even with NewPipe extractor changes that wouldn't be possible.
