### ISSUE TITLE
Can only watch a certain number of videos

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1881]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

So. Bit of an interesting bug I've got - for the past few days (About 5 days now) I've only been able to watch 2 or 3 videos in row before the site breaks. It'll load the thumbnail of the video no problem, but no matter what I do or how many times I refresh the page, it won't load. I can wait a little while and it'll start playing videos again, but then that bug comes right back and I'm stuck waiting again.

### To Reproduce

1. Open this URL at https://piped.video
2. Play a few a videos (about 2 or 3 in a row)
3. Try playing another video, and see that it doesn't load

### Expected behavior

Videos should be playing with no issue, obviously.

### Logs/Errors

N/A

### Browser, and OS with Version.

Mozilla Firefox 108.0 (aka the most current version)

**Comment by snowboundfox** [comment]
Now into day 6, and it's still doing it. Decided to not watch a 6 hour video and went over to something a little more manageable, and it's still doing it. Nothing but the thumbnail and it won't load.

**Comment by snowboundfox** [comment]
Going into day 6 and it's still doing it. Decided against watching a 6 hour video and thought to watch something a little more manageable, but the problem is still persisting. I only get the thumbnail and nothing else.

**Comment by FireMasterK** [comment]
Can you list specific video IDs, your operating system, and anything else that could be helpful to those who want to reproduce this? Watching videos longer than 6.5 hours in length might currently have issues, but I haven't tested them.

Also, list logs when the error happens from your Browser's JavaScript console if there are any.

**Comment by snowboundfox** [comment]
So when I bring up the console when I'm trying to watch a video (no matter how long that video might be), I get this:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pipedproxy-ewr.kavin.rocks/videoplayback?expire=1670982358&ei=dtaYY7rLNfia2LYPr6mIqAw&ip=45.61.174.115&id=o-AMczdEETLgf0Eo-KKolk8F-WaJz4m1KKrscqIJ_jysHA&itag=251&source=youtube&requiressl=yes&mh=ok&mm=31%2C29&mn=sn-bpb5oxu-3c2y%2Csn-ab5l6ndr&ms=au%2Crdu&mv=m&mvi=6&pcm2cms=yes&pl=24&spc=SFxXNljSnWsqSfKz9g5TwtNtU_1rJ_s&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=13796649&dur=942.061&lmt=1670924212817926&mt=1670960479&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPlLSPznBmVXALFZ1AKwOj3oShDmn3RP6SgiVy9PwvwdAiEAjkJKUEN-g_FwPLQJ8zJWYJqdq2DWPzRvqc_B_2GlASI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl&lsig=AG3C_xAwRgIhANfAnjV8CfXKlB3DJPO57iRXq5vbckT6MFJT43F2ef_fAiEAnBEMACUV9VystZkAYvmG8AtvwTBlGMqIYFrit8jxVPQ%3D&cpn=chlfrAb93JDbhDhp&host=rr6---sn-bpb5oxu-3c2y.googlevideo.com&range=0-265. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.

which is weird, because until a few days ago it was working just fine.

**Comment by FireMasterK** [comment]
Great, I think I have fixed this from my end! It shouldn't happen anymore :)
