### ISSUE TITLE
[Enhancement ] Default resolution option in preferences

### ISSUE THREAD

**Issue by OpenWick** [TeamPiped/Piped#194]
When opening YouTube  links in multiple tabs the resolution is always changing to auto irrespective of what resolution we have chosen in one tab.
 so if possible please have a default resolution option in preferences so that it wont happen.

**Comment by FireMasterK** [comment]
What is your use case for this?

Is it, for example, to set the playback quality to a higher resolution such as 1080p?

Or, is it to limit bandwidth usage?


I personally don't like the idea of having a default quality selector, but instead setup the player with a high enough initial bandwidth so that the best possible resolution is selected.

**Comment by OpenWick** [comment]
Yes Its about bandwidth usage. By default when set to auto it mostly plays at high resolution if speed is there but those who has band width limit can use the feature of setting it to low quality like 480p by default without worrying about what resolution they are on all the time. 

Ofcourse by default u can leave the resolution to auto and those who want to watch on high resolution can set it the settings if there is an option. So both sides win if the option to set default resolution in settings is there.

**Comment by FireMasterK** [comment]
Closing this with 0094ef9f15718730a2823e93a2034cad12677405.
