### ISSUE TITLE
Blank screen due to wrong MIME type

### ISSUE THREAD

**Issue by mastazi** [TeamPiped/Piped#2005]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

The feed page is completely blank

in console I can see the error

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### To Reproduce

1. Open Piped and go to the home page. In my case the feed page is set up as home page.
2. Observe the page
3. Notice how the page is completely empty

### Expected behavior

I should see Piped's UI

### Logs/Errors

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### Browser, and OS with Version.

Brave [Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit)](https://brave.com/latest/)
On Ubuntu 22.04.1 LTS

**Comment by FireMasterK** [comment]
Since this can't be reproduced on the official instance, can you provide steps for me/anyone to reproduce this issue?

**Comment by mastazi** [comment]
@FireMasterK it was actually on the official instance (sorry, I forgot to check the checkbox).

But now, I went back there and after refreshing the page I can no longer reproduce. 
Oh well I guess we can close this then.

**Comment by FireMasterK** [comment]
Interesting, what I think might have caused this is an update occuring while you load the page, odd timing if that's what happened!

**Comment by gnh1201** [comment]
I was able to reproduce this issue. The cause was server-side caching.

A server program that supports caching, such as nginx, was automatically determining and responding to the MIME format of index.js mixed with HTML code as text/html.

What the web browser wants is text/javascript, but an error occurs because it doesn't match. (The web browser seems to call this Strict MIME mode.)

To resolve this issue, you must not override the Content-Type header or enable caching depending on the URI extension in the cache profile.
