### ISSUE TITLE
Allow to be playable by yt-dlp

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#205]
You have to add <link rel="alternate" href="https://www.youtube.com/watch?v=VideoID"> so that is it playable by yt-dlp. See

https://github.com/yt-dlp/yt-dlp/commit/df0c81513e0bb37986d00c532a5ad8cef31a24ea

**Comment by FireMasterK** [comment]
This is impractical because the page is dynamically rendered with javascript. 

The better solution is to add piped.kavin.rocks as an official instance as instances are switchable directly from it and parse it from the URL directly.

The other solution is to have some kind of scheme for yt-dlp, where it can accept instructions on extracting/playing content.
