### ISSUE TITLE
Difference between Piped-Backend and youtube-dl

### ISSUE THREAD

**Issue by Klesomik** [TeamPiped/Piped#2106]
### Describe your question

I have a question which might be discussed somewhere but I can't find it.
If you know where this question is described, please give me a link.
So, what is the difference between Piped-Backend and youtube-dl project?

**Comment by n-ce** [comment]
@Klesomik 
Since no one's answering imma try to explain in short.

### youtube-dl 
- is a embeddable command line program meaning it runs in a os terminal.
- It was coded in python
- it has all the logic/algorithms inside to handle youtube stuff and give you output
- gui wrappers are available for users who arent comfortable with running programs in a terminal.

### piped-backend (actually newpipe extractor)
- is an embeddable program that was created out of the newpipe project. The newpipe android app has newpipe extractor embedded inside it and so does piped.
- is coded in java (because android)
- it has all the logic/algorithms inside to handle youtube stuff and give you output
- piped runs newpipe extractor program in cloud unlike newpipe which runs the extractor in your phone itself.

**Comment by Bnyro** [comment]
I'd keep it even easier:
* The Piped backend provides an API with the main goal of being used to watch YouTube videos
* youtube-dl on the other hand is a command line tool/library allowing users to download those video files rather than watching them directly, apart from that it supports a bunch of services other than YouTube

For additional questions, feel free to ask at the Matrix room.
