### ISSUE TITLE
Most instances can't import subscriptions, only official, and one unofficial instances

### ISSUE THREAD

**Issue by pinbuck** [TeamPiped/Piped#2274]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I had another user confirm that my test results should be repeatable, he uses google chrome on windows and my own linux install using firefox with the same exact results.

Here are my test results:
[instances.txt](https://github.com/TeamPiped/Piped/files/11144440/instances.txt)

I also tested the actual websites of each unofficial instance such as https://piped.esmailelbob.xyz/ and found there was no difference and the problem still occurs.

### To Reproduce

1. Make sure you are logged out of each instance tested, have no subscriptions loaded so far, and no changes to preferences per instance.
2. Open piped.kavin.rocks or piped.video
3. Select an unofficial instance other than piped.kavin.rocks, piped.video.
4. Attempt to import a subscription playlist without being signed in.
5. As a result, the import will not work, leaving either no response or infinite loading circle. 777.tf is the only unofficial instance and website that works importing subscriptions of any size.

### Expected behavior

Importing subscriptions should work without an account logged in.

### Logs/Errors

N/A

### Browser, and OS with Version.

Fedora 37 Linux, Firefox 111.0.1 latest version and packages up to date.
Windows 10, Google Chrome 111.0.5563.146/147, latest version

**Comment by FireMasterK** [comment]
Could you maybe share the subscriptions privately to me? I've never been able to reproduce this 🤔

**Comment by pinbuck** [comment]
I never understood why loading preferences seemed to load my subscriptions too, is that normal? I was setting it up on a friend's computer, imported my preferences, and all of my subscriptions loaded with just the preferences.json...

**Comment by thomasb22** [comment]
It's not an issue but a feature, I think ^^
In preferences.json are saved your instance with a token, and if you use on other instance without change the instance used in preferences the subscriptions are checked on the instance save in preferences.

**Comment by FireMasterK** [comment]
> I never understood why loading preferences seemed to load my subscriptions too, is that normal? I was setting it up on a friend's computer, imported my preferences, and all of my subscriptions loaded on a browser with just the preferences.json and no login included...

This is different than the issue above. Please open a new issue!

> It's not an issue but a feature, I think ^^ In preferences.json are saved your instance with a token, and if you use on other instance without change the instance used in preferences the subscriptions are checked on the instance save in preferences.

It's an unexpected bug, preferences shouldn't really include subscriptions!

**Comment by FireMasterK** [comment]
> Could you maybe share the subscriptions privately to me? I've never been able to reproduce this thinking

@pinbuck is there any way for anyone to reproduce this issue? Feed loading works with my subscriptions on all instances I tested.

However, I did notice that the video uploaded time was quite varying in different instances, which does sound worrying and I need to investigate that further.

**Comment by thomasb22** [comment]
> It's an unexpected bug, preferences shouldn't really include subscriptions!

If it's a bug, what's the token for?

**Comment by FireMasterK** [comment]
> If it's a bug, what's the token for?

That shouldn't be included either...

**Comment by Bnyro** [comment]
We're currently making a backup of the whole local storage, and as local subscriptions are stored in the local storage and not in IndexedDb or server side they get backed up to. Though I don't see a reason to remove it, as there's no real disadvantage of it? Otherwise you'd have to create two different backups doing the same thing.

**Comment by FireMasterK** [comment]
> We're currently making a backup of the whole local storage, and as local subscriptions are stored in the local storage and not in IndexedDb or server side they get backed up to. Though I don't see a reason to remove it, as there's no real disadvantage of it? Otherwise you'd have to create two different backups doing the same thing.

True, but it does feel like it's unexpected behavior? I could imagine someone losing all their subscriptions by accident, especially since there's no mention of it... Maybe we should have an option to enable/disable it or, include a warning.

Regarding auth tokens, they just shouldn't be included at all imo, for security reasons.

**Comment by FireMasterK** [comment]
> So I cleared cookies, closed my browser to wipe everything else, reopened and re-logged in to the new instance, and this time the import worked as expected. I don't know if it could be reliably reproduced just by following these steps though. OP's issue was without being logged in at all in the first place...

Imports take some time to happen as they happen asynchronously behind the scenes. In your case, the import likely took a while and was still happening. (it depends on how many subscriptions you have)

**Comment by pinbuck** [comment]
To reclarify: the way I use piped is without an account, this saves me time and keeps my password and data off of the many instances I have to switch back and fourth to when the ones I use go down.

This hasn't been a problem for me that much anymore since I started just using the two official piped.kavin.rocks for auth which don't go down too much. 
I'm able to import my subscriptions to just those two as mentioned in the issue, and have been for a while after this issue was made to seperately set any instance seperate from that as I wish.

I would still suggest any piped devs or piped instance owners to look into going accountless. (no sign-in or sign-up)
It *should* be a less resource intensive method for using piped for instances while still providing the exact same thing. This also encourages users to backup their subscriptions.json for when instances disappear for any reason.

**Comment by FireMasterK** [comment]
> This hasn't been a problem for me that much anymore since I started just using the two official piped.kavin.rocks for auth which don't go down too much. I'm able to import my subscriptions to just those two as mentioned in the issue, and have been for a while after this issue was made to seperately set any instance seperate from that as I wish.

This suggests that it might be because you had a really large subscriptions list, we were previously still using a GET request for these with the channels in the query parameters. This was 'fixed' in f2679c48136fd7c6c901a27b6ce974e16fd56bc3, to use the POST method for large subscription lists.
 
> I would still suggest any piped devs or piped instance owners to look into going accountless. (no sign-in or sign-up) It _should_ be a less resource intensive method for using piped instances... while providing nearly the exact same experience. It would also encourage users to backup their subscriptions.json for when instances disappear for any reason.

We do currently support a good out of the box experience for accountless users (every feature currently works regardless of if you use an account), though there are no plans to make it a first class feature. In the future, things like Watch History, Preferences, Channel Groups will be e2ee, and syncable with an account. Unauthenticated users actually cause more server stress and load than authenticated, due to the large queries that are necessary (that can't be avoided) — while the impact of these could be better mitigated, it requires a lot of engineering effort (which I don't have time for). #1046 would also be helpful (for both accounts, and accountless).
