### ISSUE TITLE
Legality of piped

### ISSUE THREAD

**Issue by gwenow** [TeamPiped/Piped#2293]
### Describe your question

Hello Piped Team,

I wanted to ask what the legal status of this project is. Is it legal to publicly host an instance? Who is legally liable, if at all?

Have there been cases where a Hoster of a public instance has been legally challenged? Does piped infringe Googles TOS and how? 

Or is there a FAQ or existing issue regarding this topic?

Cheers, gwen

**Comment by EHP4321** [comment]
What is the legality of watching youtube while screen sharing? Because this is basically the same thing. I think it is so obvious that it should be legal that nobody cares if it is. Obviously google should not have a say in how your browser displays their website or who you share your screen with. That said governments are just glorified gangs of robbers, so dont expect them to be reasonable.

**Comment by Bnyro** [comment]
For Piped, the same applies as https://github.com/iv-org/invidious/issues/130 and https://github.com/TeamNewPipe/NewPipe/issues/969
