### ISSUE TITLE
Sync between instances

### ISSUE THREAD

**Issue by amogusussy** [TeamPiped/Piped#2466]
### Describe the feature

This would be an option to sync settings, subscriptions, and playlists between multiple instances.
For example, I would be able to subscribe to a channel on piped.kavin.rocks, and have it also subscibe on piped.video (or any other instance).

### Why would this be useful to add?

This would make deccentralizing a lot easier, since you don't need to manually import/export subs and playlists between instancess.
This will also help stop a loss of data if one instance goes down.

### Concept(s)

You could go to the settings on `piped.kavin.rocks` and click on a settings with something along the lines of "sync data between instances". 
This then makes a field where you can copy an AuthToken, or enter an AuthToken with another instance name. 
Then you go to `piped.video` and click that same setting and paste the AuthToken from the other instance.
Then `piped.video` sends a request to `piped.kavin.rocks/sync?authToken=AuthToken` to ask for all the user's data.
Then, `piped.video` updates the subscriptions and playlists to match `piped.kavin.rocks'`.
This could work both ways.

The instance could send a request to the other instance to tell it that the subs/playlists have been update, then the other instance will also update the subs and playlists.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
>  I would be able to subscribe to a channel on piped.kavin.rocks, and have it also subscibe on piped.video

They're the same instance... They use the same API instance behind the scenes. `piped.kavin.rocks` has been deprecated since a while back.

The only officially supported way to switch instances is by using the instance switched on https://piped.video/preferences

I feel this feature request is out of scope for the time being. There could be a lot of problems if there are conflicts between the instances' synchronization.

You might as well use Piped without an account, and then switch instances in the preferences menu whenever you like.

Regarding playlists, we don't support those locally currently (and most probably never will).

I'd highly recommend choosing an instance based on whether you trust the instance operator and its uptime in https://status.piped.video/
