### ISSUE TITLE
Can we improve UI of Piped and make it more look like YT?

### ISSUE THREAD

**Issue by amiria703** [TeamPiped/Piped#2590]
### Describe the feature

Piped's UI is not so good and needs to be improved, if we make it more look like YouTube it would be great.

### Why would this be useful to add?

In overall, It'll improve UX.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned to copy YouTube, see the pinned EFY issue for a redesign effort

**Comment by FireMasterK** [comment]
You may suggest ideas to improve the UI/UX, but suggesting making a 1:1 clone of YouTube is not a goal of this project. There are definitely things YouTube does better than Piped, and we could take inspiration in many aspects. Feel free to suggest specific improvements, rather than general and vague ones.
