### ISSUE TITLE
Installing Piped as like a standalone application on Linux?

### ISSUE THREAD

**Issue by sec-19** [TeamPiped/Piped#2638]
### Describe your question

Dear Team , and users , Does anybody Knows How to Install Piped As a standalone application in Linux(Debian).
For Example , To Browse Piped , I have to go to source code directory and from there i run pnpm serve, then localhost is exposed via http://localhost:5173/. My Question is , Is there some way to not do this stuff and rather just open the app like freetube? 
I hope My Question will be answered . 
Thanks !!!!!

**Comment by Terkyz** [comment]
Uhh, it sounds silly but I guess you can host Piped on a VPS instead of using it locally? I mean, I guess you already know this but Piped is a Youtube front-end while FreeTube is an application that uses other user-hosted front-ends to play videos, and you have to do that process EVERY TIME you turn on your PC. because you are starting the server, which also must consume a lot of resources being your local machine. 

 Answering your question, I suppose you can find a Piped instance that works for you and create a PWA to access it at any time with a single click, I have no idea what DE you are using but most should allow you to do so, even the same browsers Chromium-based can do that on their own..

**Comment by dragos-efy** [comment]
To compliment what @Terkyz said, if your requirement is EASY, then these 3 options:

1. Piped has an install option in the frontend, so just install the PWA.

2. Open links in the app mode of your browser (chromium based) with something like `brave --app=https://efy.piped.pages.dev` or `chromium --app=https://piped.video` from the terminal and once you found a command you like, you just make a desktop shortcut for it that launches the app with 1 click. Firefox has a kiosk mode, but it's worse, so I'd recommend chromium for that. (I actually do this myself in brave)

3. Make an electron / tauri mini app that launches a link to Piped.

But your question is kinda flawed, Piped is a web app (if you mean the frontend at least), not "standalone", so you can only wrap it in a way that seems native, but it won't be native. Good luck!

**Comment by amogusussy** [comment]
You can use something like [PsTube](https://github.com/prateekmedia/pstube) for a GTK frontend for piped, but it will still require you to either use someone else's instance, or keep an open port on your PC.

Also, you can make a script to automatically serve piped when your PC boots, rather than doing it manually every time.
