### ISSUE TITLE
how to switch instances

### ISSUE THREAD

**Issue by voidplayer** [TeamPiped/Piped#2643]
### Describe your question

This seems very basic, but i cant find how to do it without losing everything (i logged out to login in another instance but had forgotten my password)

Id thought maybe the client would remember without being logged so it could catch up everything once logged somewhere else, but this didnt seem to be the case

In short, once that kavin.rocks is down, how could i proceed to try another instance in the simplest way possible?

Thank you!

**Comment by Bnyro** [comment]
You can do everything you can do with an account by using Piped without an account, so that all your data is stored in the browser storage. You can then simply switch instances in the preferences.

However, that also causes you to not be able to sync between devices.

From moving the data from one account to an other, you need to manually create backups of subscriptions and playlists and re-import them at the new account/instance.

Please keep in mind that exports only work when the instance is up, so it's recommended to make a backup frequently.

**Comment by voidplayer** [comment]
To add to this, i tried to login in another instance and automatically pulled everything from kavin.rocks main instance. Does this work with every instance?

I guess there is no way to backup, subscriptions, preferences and playlists at the same time. Why is it separated?

I usually just want to back up everything in case kavin.rocks goes down and being able to restore everything somewhere else
