### ISSUE TITLE
Password Lost

### ISSUE THREAD

**Issue by nightznero** [TeamPiped/Piped#2796]
### Describe your question

Helloz,i M usuing the official instance (Kevin.rocks) but lost the password. Is there any way to restore it or at least delete already existing account?

**Comment by Bnyro** [comment]
Please pm Kavin per Email or Matrix: https://github.com/TeamPiped/Piped#contact.

**Comment by FireMasterK** [comment]
The official instance doesn't do password resets I'm afraid. This is because there is no way to tell whether it's you who actually owns the account. I can't really delete your account either without your password unfortunately.

**Comment by nightznero** [comment]
> The official instance doesn't do password resets I'm afraid. This is because there is no way to tell whether it's you who actually owns the account. I can't really delete your account either without your password unfortunately.

Daaamn :/ Any info that I can provide to? Some logs i guess are collected so like when created acc,which country or so? That account is literally empty cuz before logout I didn't done anything but want to unlock my nickname :x

**Comment by FireMasterK** [comment]
> Daaamn :/ Any info that I can provide to? Some logs i guess are collected so like when created acc,which country or so? That account is literally empty cuz before logout I didn't done anything but want to unlock my nickname :x

We don't really keep any logs, so anything specific about the account would be helpful. However, if the account is empty like you said, that should be good enough!

**Comment by meiphoo7-Mae** [comment]
@FireMasterK 
I don't want to hijack this thread in any manner, but I've a very comparable problem.
I use LibreTube on my phone and created a Piped account with a rather complicated password (which I've written down). A few days ago I decided to install LibreTube on a new device and discovered that I couldn't find the password.
So now I'm in the situation that I still have full access to my account on my phone and I know every piece of information about my account (username, playlists, contents of playlists, watch history etc.) except the password.
LibreTube on my phone does know my password because it is able to login but I can't figure out where it is stored.
Is it possible for you to retrieve my password from the server because I can tell all specific details about my account so to proof it is mine is not a problem.
