### ISSUE TITLE
Live stream not working

### ISSUE THREAD

**Issue by burtek** [TeamPiped/Piped#3090]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

https://piped.video/watch?v=XFfn95WW9jw (live video) is not working. Tried in incognito and with disabled all extensions.

### To Reproduce

Go to https://piped.video/watch?v=XFfn95WW9jw

### Expected behavior

Video should play

### Logs/Errors

Uncaught (in promise) TypeError: n is undefined
    getFrame https://piped.video/assets/WatchVideo-033156e7.js:1
    showSeekbarPreview https://piped.video/assets/WatchVideo-033156e7.js:1
    setupSeekbarPreview https://piped.video/assets/WatchVideo-033156e7.js:1

### Browser, and OS with Version.

LMDE 6, FF 118.0.2

### Additional context

Live started Sept 11th, is the length an issue?

**Comment by Orygaw** [comment]
Is there any solution? This is very problematic.

**Comment by clot27** [comment]
Its strange that official instance doesnt work, while libretube (an android app built on piped api) works

**Comment by Cade66** [comment]
The only Piped instance which handles live streams is https://piped.privacydev.net/ , now and ever since other instances started to fail.
Why, I have no idea. Impossible to find an explanation. I even emailed this oddity to the owner of privacydev.net who never answered.
I've tried them all, https://piped.privacydev.net/ is the ONLY instance that does it.
Not to mention that many instances displayed on the [Piped instances page](https://github.com/TeamPiped/Piped/wiki/Instances) have been out of service for some time : why aren't they removed, at least by their owners ? Looks like they've discovered Piped, decided to join, and when their servers no longer handle Piped, they just don't care and leave their Piped instance listed : a total lack of respect.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/2898
