### ISSUE TITLE
Custom instance issue

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#3245]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Often (basically every day), loading of video/search/something else doesn’t work. When you go to settings, you’ll see "Custom Instance"
Workaround: switch instance to one that is in the list. The list changes everyday so I think it only lists working instances, and when it doesn’t work anymore it becomes "Custom Instance"

I would like that to be done automatically. If the instance is down and is now "Custom Instance", automatically switch to a working one

### To Reproduce

1. Load https://piped.video
2. Sometimes it doesn’t load videos
3. Go to settings
4. Notice custom instance

### Expected behavior

Automatically switch to  another instance

### Browser, and OS with Version.

Not applicable

**Comment by Bnyro** [comment]
When the instances API at https://piped-instances.kavin.rocks is down, it shows "Custom instance" in the settings because it can't find the currently selected instance, even though it might work just fine.

https://piped.video should still work fine as expected independently of the status of the instances API, with the restriction that you can't change the instance (which can't be avoided).

**Comment by FireMasterK** [comment]
This can also happen if the instance goes down temporarily (so it's removed from the list), which causes it to show up as a custom instance.
