### ISSUE TITLE
about pm2 support and  background service on Linux

### ISSUE THREAD

**Issue by debpalash** [TeamPiped/Piped#332]
How do you manage the **Piped** background service on Linux?

Tried this config with `pm2 `but it throws error
`Piped/ecosystem.js`
```
module.exports = {
  apps: [
    {
      name: "piped",
      script: "./node_modules/@vue/cli-service/bin/vue-cli-service.js",
      args: "serve"
    }
  ]
};
```

**Comment by FireMasterK** [comment]
You should really do `yarn build` and use nginx for serving it...

`yarn serve` is a development environment with hot-reloading so you should avoid it for daily use.

**Comment by debpalash** [comment]
> `yarn serve` is a development environment with hot-reloading so you should avoid it for daily use.

I'm familiar with what you're saying. But is it possible though? Also `yarn serve` lets me proxy through nginx along with pulling new commits easily.

**Comment by FireMasterK** [comment]
I don't quite understand the point in hosting the frontend currently. The official one is kept up-to-date and makes no contact to my servers. (Only Cloudflare Pages)

It makes more sense to host the backend than the frontend!


Although, I do plan on making a way so that anyone can host the frontend too with docker. (Although, that would be a terrible idea for my instance caching)

**Comment by FireMasterK** [comment]
You can now run `docker run -d -p 8080:80 --restart unless-stopped --name piped-frontend 1337kavin/piped-frontend:latest`

and then run watchtower to keep it up to date:
`docker run -d --name watchtower -v /var/run/docker.sock:/var/run/docker.sock --restart unless-stopped containrrr/watchtower piped-frontend`
