### ISSUE TITLE
Hardenize Piped Interface/Website Security Mess

### ISSUE THREAD

**Issue by TNTBOMBOM** [TeamPiped/Piped#363]
Hi There,

Im checking the main website security surface and its missing tons of features which are important in nowadays modern security needs. 

https://www.hardenize.com/report/piped.kavin.rocks/1629076232#www_http
https://www.hardenize.com/report/piped.kavin.rocks/1629076232#www_tls
https://www.hardenize.com/report/piped.kavin.rocks/1629076232#www_hsts
https://www.ssllabs.com/ssltest/analyze.html?d=piped.kavin.rocks&s=172.64.166.36
https://cryptcheck.fr/https/piped.kavin.rocks

TLS: 

- No http force redirection to https
- Disable TLS 1.0 , 1.1 as they are considered deprecated since 2020
- Allow TLS 1.3 (useful for ESNI/ECH whenever ready)
- Disable weak ciphers
- No hsts/hsts-preload 

https://www.hardenize.com/report/piped.kavin.rocks/1629076232#domain_dnssec
https://www.hardenize.com/report/piped.kavin.rocks/1629076232#domain_caa

DNS: 

- No DNSSEC
- No CAA (since you are using cloudflare then this considered as hard/not applicable, but whenever you consider to deprecate cloudflare please consider supporting it)

https://www.hardenize.com/report/piped.kavin.rocks/1629076232#www_csp
https://securityheaders.com/?q=https%3A%2F%2Fpiped.kavin.rocks%2F&followRedirects=on
https://www.hardenize.com/report/piped.kavin.rocks/1629076232#www_xfo
https://www.hardenize.com/report/piped.kavin.rocks/1629076232#www_xxssp
https://www.hardenize.com/report/piped.kavin.rocks/1629076232#www_xcto

Webapp sec , headers , csp..: 

- Self explanatory. 

Websites to look and take examples from:  

danwin1210:
https://www.hardenize.com/report/danwin1210.me/1628389257
https://www.ssllabs.com/ssltest/analyze.html?d=danwin1210.me&s=116.202.17.147&latest
https://cryptcheck.fr/https/danwin1210.me
https://securityheaders.com/?q=danwin1210.me&followRedirects=on

grapheneos:
https://www.hardenize.com/report/grapheneos.org/1628592032
https://www.ssllabs.com/ssltest/analyze.html?d=grapheneos.org&s=192.99.43.50
https://cryptcheck.fr/https/grapheneos.org
https://securityheaders.com/?q=grapheneos.org&followRedirects=on

...etc

ThX!

**Comment by FireMasterK** [comment]
A significant portion of things don't matter here / are already done.


> No http force redirection to https

Not under my control, however, we're already preloaded so Firefox and Chromium are not affected. Only Safari is.

> Disable TLS 1.0 , 1.1 as they are considered deprecated since 2020

Not under my control since I use Cloudflare pages.

> Allow TLS 1.3 (useful for ESNI/ECH whenever ready)

It's already allowed.

> No hsts/hsts-preload

We're already preloaded, although HSTS headers can't be sent due to technical reasons.

> No DNSSEC

That's false. DNSSEC is enabled. https://dnssec-analyzer.verisignlabs.com/kavin.rocks

> No CAA

Added for Let's Encrypt.

> Webapp sec , headers , csp

Not Applicable for Piped due to its site architecture, dompurify is used to prevent XSS attacks.

**Comment by TNTBOMBOM** [comment]
> Not under my control since I use Cloudflare pages.

There is a way to do that through cloudflare: 

https://community.cloudflare.com/t/how-do-i-disable-tls-1-0/2670/10

https://blog.cloudflare.com/deprecating-old-tls-versions-on-cloudflare-dashboard-and-api/

>  That's false. DNSSEC is enabled. https://dnssec-analyzer.verisignlabs.com/kavin.rocks

something is wrong when it comes to piped (not sure why) check: 

https://dnssec-debugger.verisignlabs.com/piped.kavin.rocks

https://dnsviz.net/d/piped.kavin.rocks/dnssec/

**Comment by FireMasterK** [comment]
> There is a way to do that through cloudflare:

I use Cloudflare pages, which technically I can't change TLS settings for. If you see another subdomain, like pipedapi.kavin.rocks, it should pass just fine.

> something is wrong when it comes to piped (not sure why) check:

Looks like the CNAME to `piped.pages.dev` has issues, because `pages.dev` doesn't support it, It's not in my control, however I will see if Cloudflare's support can do anything about it.
