### ISSUE TITLE
CORS and 502 error behind Nginx as Proxy

### ISSUE THREAD

**Issue by satoshinotdead** [TeamPiped/Piped#3639]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Following the official guide on Docker Compose, I encountered an error in the browser console when trying to view videos.

I'm curious why Nginx is included if we also need to use Nginx on the server. How can we locally expose the host to avoid these errors?

### To Reproduce

Install following the official guide and use Nginx as proxy.

### Expected behavior

Avoid redundant Nginx instances.

### Logs/Errors

`The Same Origin Policy disallows reading the remote resource at https://privateinstance.com/feed/unauthenticated?channels=. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502`

### Browser, and OS with Version.

Linux server, last version.

**Comment by Bnyro** [comment]
You can host it without the "duplicated" nginx when just including the configuration from https://github.com/TeamPiped/Piped-Docker/tree/main/template (all the .conf files) in your own nginx config and change the ports as I've described here: https://github.com/TeamPiped/Piped-Docker/issues/38#issuecomment-2127482371. (you will also have to change the ports in the nginx .conf files).

If you need specific help with issues you encounter when trying to host Piped, please ask such at https://matrix.to/#/#piped:matrix.org.

**Comment by Bnyro** [comment]
Piped is including its own nginx container by default so that people with few self-hosting knowledge are able to host Piped with minimal efforts - if you know what you're doing it shouldn't be hard for you to make the changes necessary to use the system nginx.

**Comment by hanscees** [comment]
I think it is impossible to use a reverse proxy on another host and snip out the nginx in the middle. 
The nginx in the middle uses a unix socket, which only works when on the same host between docker containers.

I might be wrong but I think the current docker setup is incompatible with a separate nginx or other reverse proxy. With separate I mean it runs on another host/vm. You can't solve the cors problems because your api adds cors headers probably.

If I use my reverse nginx proxy and add headers the errors are: 

Access to fetch at 'http://vodapi.hanscees.com/streams/4yvzJBr7TEw' from origin 'http://vod.hanscees.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

It would be nice to add this to your documentation if true.

**Comment by hanscees** [comment]
Oh how nice, I was wrong and have a working config now. 

My reverse proxy in nginx and is at 192.168.0.110
My host / vm with the piped docker is at 192.168.0.29

the configs are below. 

```
server {
    listen 80;
    server_name vod.hanscees.com; # must go to pipedfrontend
    set $backend "http://192.168.0.29:8081";

    location / {
        proxy_pass $backend;
        proxy_http_version 1.1;
        proxy_set_header Connection "keep-alive";
        proxy_set_header Host $host; 
    }
}

### api 
server {
    listen 80;
    server_name vodapi.hanscees.com;
    set backend "http://192.168.0.29:8082";

    location / {
        #proxy_cache pipedapi;  ##deosnt work somehow 
        proxy_pass $backend;
        proxy_http_version 1.1;
        proxy_set_header Connection "keep-alive";
        sub_filter '&ump=1' '';
        sub_filter_once off;
        sub_filter_types application/json;
    }
}
                                
server {                     
    listen 80;               
    server_name vodprox.hanscees.com; # stays the same
                                                                                
    location / {                                                                
       proxy_pass http://192.168.0.29:8080;                                  
       proxy_set_header Host $host;                                             
    }                                            
}   
```

docker-compose.yml
```
server {
    listen 80;
    server_name vod.hanscees.com; # must go to pipedfrontend
    set $backend "http://192.168.0.29:8081";

    location / {
        proxy_pass $backend;
        proxy_http_version 1.1;
        proxy_set_header Connection "keep-alive";
        proxy_set_header Host $host; 
    }
}

### api 
server {
    listen 80;
    server_name vodapi.hanscees.com;
    set backend "http://192.168.0.29:8082";

    location / {
        #proxy_cache pipedapi;  ##deosnt work somehow 
        proxy_pass $backend;
        proxy_http_version 1.1;
        proxy_set_header Connection "keep-alive";
        sub_filter '&ump=1' '';
        sub_filter_once off;
        sub_filter_types application/json;
    }
}
                                
server {                     
    listen 80;               
    server_name vodprox.hanscees.com; # stays the same
                                                                                
    location / {                                                                
       proxy_pass http://192.168.0.29:8080;                                  
       proxy_set_header Host $host;                                             
    }                                            
}   
```

**Comment by satoshinotdead** [comment]
> Oh how nice, I was wrong and have a working config now.
> 
> My reverse proxy in nginx and is at 192.168.0.110 My host / vm with the piped docker is at 192.168.0.29
> 
> the configs are below.
> 
> ```
> server {
>     listen 80;
>     server_name vod.hanscees.com; # must go to pipedfrontend
>     set $backend "http://192.168.0.29:8081";
> 
>     location / {
>         proxy_pass $backend;
>         proxy_http_version 1.1;
>         proxy_set_header Connection "keep-alive";
>         proxy_set_header Host $host; 
>     }
> }
> 
> ### api 
> server {
>     listen 80;
>     server_name vodapi.hanscees.com;
>     set backend "http://192.168.0.29:8082";
> 
>     location / {
>         #proxy_cache pipedapi;  ##deosnt work somehow 
>         proxy_pass $backend;
>         proxy_http_version 1.1;
>         proxy_set_header Connection "keep-alive";
>         sub_filter '&ump=1' '';
>         sub_filter_once off;
>         sub_filter_types application/json;
>     }
> }
>                                 
> server {                     
>     listen 80;               
>     server_name vodprox.hanscees.com; # stays the same
>                                                                                 
>     location / {                                                                
>        proxy_pass http://192.168.0.29:8080;                                  
>        proxy_set_header Host $host;                                             
>     }                                            
> }   
> ```
> 
> docker-compose.yml
> 
> ```
> server {
>     listen 80;
>     server_name vod.hanscees.com; # must go to pipedfrontend
>     set $backend "http://192.168.0.29:8081";
> 
>     location / {
>         proxy_pass $backend;
>         proxy_http_version 1.1;
>         proxy_set_header Connection "keep-alive";
>         proxy_set_header Host $host; 
>     }
> }
> 
> ### api 
> server {
>     listen 80;
>     server_name vodapi.hanscees.com;
>     set backend "http://192.168.0.29:8082";
> 
>     location / {
>         #proxy_cache pipedapi;  ##deosnt work somehow 
>         proxy_pass $backend;
>         proxy_http_version 1.1;
>         proxy_set_header Connection "keep-alive";
>         sub_filter '&ump=1' '';
>         sub_filter_once off;
>         sub_filter_types application/json;
>     }
> }
>                                 
> server {                     
>     listen 80;               
>     server_name vodprox.hanscees.com; # stays the same
>                                                                                 
>     location / {                                                                
>        proxy_pass http://192.168.0.29:8080;                                  
>        proxy_set_header Host $host;                                             
>     }                                            
> }   
> ```
> 
> had errors where the gets where not going to the proxy: this was an error I made in config/config.properties

So, you changed the ports on docker-compose.yml but pasted the Nginx template two times? (:

Thanks for sharing. I appreciate it!

**Comment by satoshinotdead** [comment]
Still not working, 502 errors.

I'm using the same host with different domains because this fork of Invidious works this way.

**Comment by hanscees** [comment]
Hi satosalive,

I got to the error by watching errors in the browser while visiting the website, so by using developerstools. 
I have many domains too on my reverse nginx, so that should not be a problem.

And you don't need the api or proxy. You can host the webfrontend and point it in the settings (using your browser) to one of the api servers listed. 

So troubleshoot options are:
1. look at log in your browser developers options
2. use front end with a working api server, using preferences in your browser
3. if that works fine (your frontend with another api server), point to your own api server and look at the errors (if any of course) in developers tools in your browser again. 

lewt ne know what happens

**Comment by satoshinotdead** [comment]
So _API_ server configured on Piped instances could point from Nginx to _backend_ on docker-compose file?

> I really like when devs use the same term everywhere (:

So, I can host API (backend) and Piped (frontend) without the proxy that I'm already hosting. Is that OK?

**Comment by hanscees** [comment]
I dont understand you due to vague words / concepts.

The docker piped config has 3 http parts:
1. nginx. This server is needed to get to the piped proxy: they are connected by a unix socket (so a file connection)
2. piped-frontend
3. piped-backend or also called piped-api

when you have a reverse NGINX proxy in front of it  that is the fourth http part. 

connections go like this: 

A. reverse proxy ---> frontend.  

In the frontend you can either connect to an external api, or to your own.

To host your own api/backend you need
B. reverse proxy --> api/backend. The backend then in its config refers to the proxy  
C. reverse proxy ---> nginx  --> unix socker --> proxy   

I think that is how it works

**Comment by satoshinotdead** [comment]
Hey, thanks for your following up and sorry about the vague concepts. I just want to use my existing Nginx proxy to route the backend and frontend to internet without using Docker Compose, as I am already hosting Nginx for other services.

I'm currently hosting both the backend and frontend, but I'm encountering CORS issues that need to be resolved. Do I need to allow (CORS related) the backend domain on the frontend? 

I hope someone can contribute to this :)
