### ISSUE TITLE
Self-host without docker

### ISSUE THREAD

**Issue by rderensy** [TeamPiped/Piped#398]
Hi,

Would it be possible to self-host Piped without using docker? I have VMs for every service I have and I don't want to run docker directly on Proxmox (and running docker inside a VM seems stupid). I have no idea about what packages to install or what to configure, I've never really worked with Docker and I'm not sure I understand what's in the docker-compose files (is doesn't seem to install anything).

Do you have simple instructions on how to? I believe the docker is already using Debian so it shouldn't be complicated to run on a "real" Debian.

Thanks!

**Comment by FireMasterK** [comment]
No, sorry but without docker you'll have a really bad time maintaining an up-to-date instance.


With docker, you deploy once and it's automatically kept upto date.

**Comment by Brawl345** [comment]
I'm replying to this since it's the first search result on Google and the above comment is nonsense.

It's just a Vite project, so install yarn, run `yarn install --prefer-offline` followed by `yarn build` and you can find the full site in the `dist` folder. You can also take a look at the Dockerfile on how it's build: https://github.com/TeamPiped/Piped/blob/master/Dockerfile#L10 (also it replaces google's font URL with the dev's one, which is not good for privacy... dunno why they are not embedded into the SPA).

Remember you need to regularly rebuild on updates.

**Comment by Brawl345** [comment]
>All I'm trying to do is save you the trouble of spending hours of your life managing an instance

I think people can decide for themselves.

>you're missing the [proxy](https://github.com/TeamPiped/http3-ytproxy), the [backend](https://github.com/TeamPiped/Piped-Backend)

This I did not know because it's not stated anywhere and just building the frontend worked but it does in fact contact `kavin.rocks` for everything.

>Because clearly connecting to Google's servers for it would be a worse idea

I haven't said that it should use Google.
