### ISSUE TITLE
Change of project name

### ISSUE THREAD

**Issue by peepopoggers** [TeamPiped/Piped#455]
I am afraid to suggest people to use piped as.. well it sounds kinda funny.
Like - "Hey mom, you should use piped to watch videos"
It sounds a bit strange, yknow?

Changing the entire name would be a bit OTT but a prefix could be added or something.
Thoughts?

**Comment by unbeatable-101** [comment]
Sounds no weirder than youtube to me

**Comment by FireMasterK** [comment]
The name was though about from on finding words with 2-3 syllables at most. The rationale being that it should be easy to remember and pronounce.

I feel like adding a prefix would be counter intuitive to that.

I don't think I would end up changing the name anytime soon, especially since I'm not a creative person with names, and this name took 2-3 months to figure out in the first place!

**Comment by peepopoggers** [comment]
:thinking: Alright
