### ISSUE TITLE
Add ability to disable haveibeenpwned

### ISSUE THREAD

**Issue by unixfox** [TeamPiped/Piped#497]
- I don't really want to send half of my hashed password to haveibeenpwned.
- I know some users that don't care if they use a compromised account.

**Comment by FireMasterK** [comment]
I'd like to clarify a misconception here, Piped, does not send HALF of your hashed password to haveibeenpwned.

Piped sends the first 5 characters of a sha1 hash, which are 40 bytes big, so that's roughly just 12.5% of your hash.

For example, even something as simple as https://api.pwnedpasswords.com/range/00000 returns close to 700+ hits

You can read more about the process at https://en.wikipedia.org/wiki/K-anonymity

I've added a configuration property to disable it in case you don't want it for whatever reason at https://github.com/TeamPiped/Piped-Backend/commit/a1a3e717b2e0581de3be3640edcef2e54218e357.
