### ISSUE TITLE
New UI progress tracking

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#520]
You can test the new UI at https://ui-v2.piped.pages.dev/

Todo:

- [ ] Loading states
- [ ] Animations
- [ ] ...

Feedback on the new UI is requested!

**Comment by Loki-L1130** [comment]
Search Function does not seem to be Working for English Language.

**Comment by Mhowser** [comment]
expanding and contracting the left hamburger menu is choppy.

**Comment by filipesmedeiros** [comment]
hmm i will have to test properly

doesn't seem to be a problem for me at all: macbook air m1 16gb | firefox 93

**Comment by filipesmedeiros** [comment]
it definitely doesn't look like that for me! weird 👀

**Comment by filipesmedeiros** [comment]
hmmm let me try with no animation

**Comment by ChunkyProgrammer** [comment]
The log out button at the bottom of the nav menu should have translatable text instead of being hard coded

**Comment by filipesmedeiros** [comment]
yes! will fix, thank you @ChunkyProgrammer

**Comment by openwick** [comment]
@IvRRimum Wow its great but few suggestions if u can tweak. When I double tap, the black play pause button is coming so if u can stop it when double tapping that would be nice.
Also on firefox android when double tapping, the copy paste options for clip board are popping up and I don't know why but its not an issue on bromite which is essentially chrome. 
![Screenshot_2021-10-19-15-59-36-673_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/78715124/137892910-aa8c8e09-0667-4650-8d6d-cfb983636db6.jpg)

I hope @FireMasterK implement something like this so piped will be great on mobile compared to invidious

**Comment by kreha1** [comment]
- clicking back on preferences page will move you to the root page instead of whatever you did previously
- there is no searchbar on the video page (there is on figma design)
- the video suggestion section is too narrow, resulting in many unnecessary line breaks
- the font size is too big in most of instances, let's focus on the comment section:
  - username: 14px vs 13px
  - body: 16px vs 14px
  - like count 14px vs 12px
  - timestamp: 14px vs 12px + I believe that having it on a separate line is a waste of space
I think that YT design team has struct a nice balance when it comes to the font size and line space.
YT:
![obraz](https://user-images.githubusercontent.com/3883601/146619589-5fd826d6-82b0-4b76-8ad9-e1d354401be5.png)
Piped:
![obraz](https://user-images.githubusercontent.com/3883601/146619633-a5bfbbee-4808-4132-a201-e43f3943d26f.png)

Here's Piped after a quick change in devtools:
![obraz](https://user-images.githubusercontent.com/3883601/146620399-fd1b7013-e91a-4355-adeb-c03435b1417b.png)

On a technical front, I'd recommend using [unocss](https://github.com/antfu/unocss) for quick development and more tailored styling instead of relying on the predefined styles from a library - I know how tedious it gets when you stray from the path of your css framework of choice.

I would gladly help with the transition, along with providing fixes for those issues I've highlighted if you are interested,

**Comment by sdfg2** [comment]
The vertical nav bar takes up way too much space for what it contains, especially when you consider how little space the same elements take on the current layout.  Even folded in it's a massive bar containing what, 5 or 6 icons?  

I like the colours, it's almost identical to my desktop scheme! :-D 

Is the player part of this project as well or is that something separate?  There are a few issues with it.

**Comment by MintMain21** [comment]
Since ya'll are rewriting the UI for Piped already, I have one suggestion.

Separate the code of the comment section/recommended video section from the rest of the page so that individuals (like myself) can create uBlock filters to block them instead of having to use webpage cookies. 

That way, I don't have to disable the comments everytime I open a Private Browsing session.

**Comment by MintMain21** [comment]
Can we have buttons on the search results to open videos/playlists in YouTube, similar to the buttons for opening videos in Audio Only mode?

**Comment by 65wat** [comment]
…
> 
> I think that YT design team has struct a nice balance when it comes to the font size and line space. YT: ![obraz](https://user-images.githubusercontent.com/3883601/146619589-5fd826d6-82b0-4b76-8ad9-e1d354401be5.png) Piped: ![obraz](https://user-images.githubusercontent.com/3883601/146619633-a5bfbbee-4808-4132-a201-e43f3943d26f.png)
> 
> Here's Piped after a quick change in devtools: ![obraz](https://user-images.githubusercontent.com/3883601/146620399-fd1b7013-e91a-4355-adeb-c03435b1417b.png) I haven't changed the video thumbnail bit, outside of giving it more place to breathe (70/30 vs 80/20 previously). I personally feel, again, that YT nailed the thumbnails, as you can pack much more of them in the same space, and that aligns with their purpose, that is suggesting a video.
> 
…

I just wanted to say that I am strongly in favor of the default piped design choice (meaning the first image above, before the change in devtools). The slightly increased space between username/timestamp and comment text improves readability and clarity to me.

Also: is it possible to make the play/pause button translucent or make it hide faster after clicking play (or both)? The button often blocks video content as it fades out.

Lastly: I want to thank all contributors for this project. I absolutely love it. It’s the best youtube UI ever :)

**Comment by Mhowser** [comment]
> I just wanted to say that I am strongly in favor of the default piped design choice (meaning the first image above, before the change in devtools). The slightly increased space between username/timestamp and comment text improves readability and clarity to me.

How about a compromise? There should be an option to have a standard layout and a compact layout, this could be changed in preferences. I prefer the compact one since I use Piped on a small mobile screen.

**Comment by Loki-L1130** [comment]
Search UI is totally Broken. I mean it is out of the place where it should be.

**Comment by TanKot** [comment]
Please make the dark mode black, if possible.
This purple or whatever ain't looking that good.

**Comment by IronMaltese** [comment]
When searching for a channel, the channel icon should be a circle

**Comment by cypherpunk1984** [comment]
I would put the sidebar as a topbar like Piped-material did: https://piped-material.xn--17b.net/
It doesn't take any side space, so we can keep watching videos in a 'theater mode', that uses pretty much the whole width of the screen without having to switch to full screen.

**Comment by MintMain21** [comment]
An option to minimize video recommendations on Desktop, similar to on Mobile, would be nice.

**Comment by debpalash** [comment]
Search result page has Filter button absurdly big. Found the css issue, it has harcoded height of 100%

![image](https://user-images.githubusercontent.com/4178343/164532414-1eec01e7-c764-44d3-9f69-6e1a63ed9f77.png)

![image](https://user-images.githubusercontent.com/4178343/164532963-de5b6fb9-9526-4736-8200-579bf1d5ed3e.png)

**Comment by fasduswisdom** [comment]
![image](https://user-images.githubusercontent.com/57533365/168726031-f019a5bc-dc0e-433c-8cb4-73087c0996be.png)
and my late 2009 theme got murdered by this layout change

**Comment by pklion** [comment]
![image](https://user-images.githubusercontent.com/78145811/171839410-05f7cf45-f7e4-47b3-8ba9-6810a1ed2225.png)
"Subscriptions" button in Feed page doesn't looks good...

**Comment by pklion** [comment]
Also, top bar appears in embed page though it shouldn't be there.
(Using LibRedirect)
![image](https://user-images.githubusercontent.com/78145811/171997011-7a789949-8753-4824-9d5d-a8458279975b.png)

**Comment by hommegithub** [comment]
Just wondering if the project is dead or someone from the dev team has responded? Asking because I am new to posting on GitHub

**Comment by nonetrix** [comment]
> Just wondering if the project is dead or someone from the dev team has responded? Asking because I am new to posting on GitHub

The project as a whole? seems active 

I don't know about UI update
![Screenshot 2022-07-31 at 22-50-11 TeamPiped_Piped An alternative privacy-friendly YouTube frontend which is efficient by design](https://user-images.githubusercontent.com/45698918/182068721-d4e66b36-d153-4874-b1c0-b1835a6f4708.png)

**Comment by Bnyro** [comment]
Deprecated in favour of EFY UI
