### ISSUE TITLE
Raspberry pi 4 arm64 archlinux

### ISSUE THREAD

**Issue by sdanfa** [TeamPiped/Piped#548]
Hello,
How can I use it on selfhosted ip on rpi4 arm64 archlinux? Do you have a working docker image for arm64?

Thanks.

**Comment by FireMasterK** [comment]
Since you're using a raspberry pi, make sure you are reachable over the Internet, this is important for Piped to function properly.

1. clone https://github.com/TeamPiped/Piped-Docker
2. Run `./configure-instance.sh`
3. Replace `1337kavin/piped:latest` with `1337kavin/piped:hotspot` in the docker-compose.yml file.
4. Now, a simple docker-compose up -d is all you need!
