### ISSUE TITLE
Add option for "Cast to Device"

### ISSUE THREAD

**Issue by Mhowser** [TeamPiped/Piped#681]
I see there is an option for Airplay for IOS devices, but no cast option for other devices. It would be great if this could be added.

**Comment by FireMasterK** [comment]
Cloud you verify that https://github.com/TeamPiped/Piped/pull/682#issuecomment-997098397 fixes the issue? (The cast button should appear when you have visible devices.)

**Comment by FireMasterK** [comment]
Looks like this feature requires Google's Cast SDK, which is proprietary code, and require's google's servers, I'm not too happy with including it.

**Comment by Mhowser** [comment]
Dang that sucks, is there an alternative protocol that would be sufficient?

**Comment by Mhowser** [comment]
From Wikipedia; "AirPlay is a **proprietary wireless communication protocol** stack/suite developed by Apple Inc. that allows streaming between devices of audio, video, device screens, and photos, together with related metadata."

Since Airplay is also a proprietary protocol, why is this allowed when Goggle cast is basically the equivalent?

**Comment by FireMasterK** [comment]
It's quite simple why:

- AirPlay is implemented as a native web API as seen in https://developer.apple.com/documentation/webkitjs/adding_an_airplay_button_to_your_safari_media_controls.
- Chromecast / Cast requires javascript from google's servers since a library is required for it - https://developers.google.com/cast/docs/web_sender.

**Comment by Mhowser** [comment]
I understand now, thanks for the info!

**Comment by FireMasterK** [comment]
I'm closing this due to the reasons mentioned above.
