### ISSUE TITLE
[Feature Request P4+] Ability to leave comments

### ISSUE THREAD

**Issue by lua-rocks** [TeamPiped/Piped#695]
It would be _awesome_ if at some point in the future you could add the ability to leave comments under videos exclusively for your site users, independent from YouTube, without any censorship, but with very simple spam protection, like this:

each user can leave no more than

+ **1** comment under the same video;
+ **3** comments under other people's comments on the same video.

Something like that 😋

**Comment by Mhowser** [comment]
That seems like a huge liability for this project, just imagine how quickly things can get out of hand with an uncensored comment section.

**Comment by kreha1** [comment]
The "coolest" and most privacy-focused way to do that would be to use [Cactus Comments](https://cactus.chat/). It's a FOSS alternative to Disqus, based on the [Matrix Protocol](matrix.org/).
However, as far as I can tell (based on its demo), the frontend doesn't provide threaded messaging. I know that first-party matrix client - Element - [doesn't either](https://github.com/vector-im/element-web/issues/2349). So that would require forking the [frontend code](https://gitlab.com/cactus-comments/cactus-client) and implementing the feature. I don't know Elm so can't really deduce it by reading the source code.

**Comment by lua-rocks** [comment]
@Mhowser I believe that fair censorship is a liability. If someone writes something awful, he is personally responsible for his words and nobody else. In my opinion, not even the state has the right to limit a person's freedom of speech.

**Comment by Mhowser** [comment]
If some nutjob makes death threats, or posts malicious links to illegal content such as CP, I highly doubt they will take personal responsibility for their comments. Someone else will have to moderate.

**Comment by lua-rocks** [comment]
@Mhowser To some extent you are of course right, but personally I think that understanding what kind of society we live in is very useful, even if unpleasant, and such posts should be closed only at the request of the government. It is their liability to moderate such incidents, not yours and not mine.

**Comment by Bnyro** [comment]
There are no plans to implement something like this, it would also require some sort of moderation tooling which is beyond scope.
