### ISSUE TITLE
Reduce space taken by the video

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#71]
The video takes more than a screen with the navbar, you should reduce the space (with width css attribute probably)

**Comment by FireMasterK** [comment]
Additionally, the player keeps resizing whenever it changes quality.

**Comment by FireMasterK** [comment]
Cold you check if this has been fixed? I added some css to limit the size.

**Comment by B0pol** [comment]
No, it isn't. I'm talking about desktop here btw

**Comment by FireMasterK** [comment]
Could you send a screenshot perhaps? I think I'm not understanding what you mean here. (or we could just discuss in matrix)

**Comment by moriel5** [comment]
I'm joining this bug report.
This only happens to me on Edge, not on Firefox.

Edge:
![Screenshot from 2021-04-18 21:16:50](https://user-images.githubusercontent.com/20175297/115156112-518f6500-a072-11eb-9587-fff94e9a0625.png)

Firefox:
Pending for now, since Piped has stopped sending me videos and thumbnails altogether (probably a network issue on my end).

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/115262595-51669680-a152-11eb-976d-f098cc8fa39c.png)
![image](https://user-images.githubusercontent.com/20838718/115263032-b3270080-a152-11eb-92b9-bbed9d86d50f.png)

I couldn't replicate this on Edge, strange.

**Comment by moriel5** [comment]
Really odd.
I'll try and look at what may be the culprit once our internet connection returns (it appears that the issue lies with the DSL provider connection to the ISPs (including ours).

**Comment by moriel5** [comment]
It turns out that my issue, is due to having Ultrawidify enabled (I keep forgetting to configure it for streching to 16:10, 16:9, 5:4, and 4:3), which quite surprised me, as I usually keep it disabled.

The issue also happens on Firefox with it enabled, so I'll notify the extension's author, as this is a bug with the extension, not Piped.
