### ISSUE TITLE
Fix Instances Wiki

### ISSUE THREAD

**Issue by Loki-L1130** [TeamPiped/Piped#716]
Remove api from the URLs of all Instances in the list if clicked barely without removing it returns a 404 Error.

**Comment by TheSilkky** [comment]
The instance list is dynamically phrased by the frontend, so you can switch instances in the settings. Removing the api url would break this feature.

Maybe the instance list could be improved to include the frontend url and also making it easier to find by adding it to README.md, instead of a wiki page?

**Comment by FireMasterK** [comment]
You're expected to switch instances via the preferences menu, using a 3rd party's hosted frontend will never be supported due to me not wanting to deal with AGPL violations, and to minimize potentially unsafe JS code for users (in case of a malicious instance).

**Comment by TheSilkky** [comment]
I think this just creates a lot of confusion for the users (eg. This issue), it severely reduces the amount of people using other instances and also inherently gives users less choice eg. Wanting to use an instance without Cloudflare.

**Comment by Loki-L1130** [comment]
@FireMasterK I mean that adding the word api in URL returns a 404 Error when clicked from the Wiki.

If I change the Instance in Preference does Piped extract videos from the Instance but under the piped.kavin.rocks Domain - Right ?

**Comment by TheSilkky** [comment]
That's expected since your not opening the web frontend but instead api of the instance, If you where to go [here](https://api.piped.silkky.cloud/trending?region=US) you would get the raw JSON reponse for the trending page.

Yes, if you set the instance in settings Piped will get all it's data, including accounts from the selected instance.

**Comment by Loki-L1130** [comment]
@TheSilkky 

> Yes, if you set the instance in settings Piped will get all it's data, including accounts from the selected instance.

Under the same domain I am using right ?

> That's expected since your not opening the web frontend but instead api of the instance,

But the Wiki was supposed to help users chosose Instance so it should be without `api`

**Comment by TheSilkky** [comment]
> Under the same domain I am using right ?

Yes, it's still under the same frontend domain.

> But the Wiki was supposed to help users chosose Instance so it should be without `api`

The frontend gets the list of instances from the wiki page. It uses the api url because that's the url the frontend needs to change what instance your using.

**Comment by Loki-L1130** [comment]
@TheSilkky I understand that the Instances WIki is made for changing instances within the frontend.

@FireMasterK Now, I understand what you mean by the AGPL Violations.
