### ISSUE TITLE
Ability to set and save a default playback speed

### ISSUE THREAD

**Issue by Latrolage** [TeamPiped/Piped#725]

**Comment by FireMasterK** [comment]
Buy changing it when playing a video retains it for other videos, so isn't this already implemented?

**Comment by FireMasterK** [comment]
Could you let me know if https://rate-change-fixes.piped.pages.dev/ fixes the issue?

**Comment by Latrolage** [comment]
After closing the browser window and coming back, it's set back to 1.0x speed again.

**Comment by sdfg2** [comment]
The problem is nothing is 'saved' to the account other than the subscriptions.  Not even watched videos.

I like this idea, and I'd like to extend it to a per-channel setting - there are huge variations in how much some channels speed up the speech, I have to do this back and forth depending on what I'm watching.  But that would mean properly implementing user accounts.

**Comment by FireMasterK** [comment]
Closing this with #1573.
