### ISSUE TITLE
Add my instance

### ISSUE THREAD

**Issue by moom0o** [TeamPiped/Piped#737]
I couldn't edit the wiki. Please add https://piped.moomoo.me/
I'm using BuyVM in New York City, USA, Cloudflare CDN with SSL set to Full, and letsencrypt for SSL.

If you need:
API: https://pipedapi.moomoo.me/ 
Proxy: https://pipedproxy.moomoo.me/

**Comment by FireMasterK** [comment]
Added, thanks for hosting an instance!

<br />
I noticed a few optimizations/improvements that could be done since you are using Cloudflare:
<br />
1- Enable Cache Everything via a Page Rule:

![image](https://user-images.githubusercontent.com/20838718/149768113-8fc0bba1-b907-4e93-8682-b7c6034319b3.png)

**Note**: You need to remove varnish when you make this change, remove the `varnish` service from `docker-compose.yml` and edit `config/pipedapi.conf` to replace `varnish:80` with `piped:8080`

2- Respect existing headers for Cache:
![image](https://user-images.githubusercontent.com/20838718/149770541-5140bd9a-121c-4e65-ae6c-7321a2164657.png)

3- Remove Origin header, for better/more cache hits:
![image](https://user-images.githubusercontent.com/20838718/149771039-87a961d8-1e0a-45f4-8839-c20f6c5c5acf.png)

3- Use `Full (strict)` to protect against MITM attacks:

Your setup of Full uses TLS to your origin server but doesn't protect it against MITM attacks, although it protects against snooping.

You should ideally use their Origin Certificates instead of Let's Encrypt with the SSL mode changed.

**Comment by FireMasterK** [comment]
Hey @moom0o,

Your instance has been offline for a few days now, are you still interested in hosting an instance?

**Comment by moom0o** [comment]
Hi, I started it back up (probably crashed or something?) I moved it to a Hetzner VPS, since my current BuyVM vps is a little slow, and probably doesn't have enough ram. Change the country to Germany
