### ISSUE TITLE
Docker without the built-in reverse proxy?

### ISSUE THREAD

**Issue by R8s6** [TeamPiped/Piped#850]
Hi,

My gateway already has a reverse proxy and is terminating SSL, so I only need to run the a piped docker instance without another reverse proxy.

Is this something possible? If so, can I ask how to do it?

Thanks!

**Comment by FireMasterK** [comment]
You should use docker aio with nginx, that only uses http, with a requirement for a reverse proxy with tls termination.

**Comment by FireMasterK** [comment]
Can I close this issue? Did that help?

**Comment by rderensy** [comment]
I don't know about him but I'm having the same problem. I have a dedicated reverse proxy for all my domains, which handles TLS and I can't get it to work.

[The doc](https://piped-docs.kavin.rocks/docs/self-hosting/) says 

````
server {
    listen 80;
    server_name hostname; # For all 3 hostnames

    location / {
       proxy_pass http://127.0.0.1:8080;
       proxy_set_header Host $host;
    }
}
````

So I am guessing `# For all 3 hostnames` means `server_name piped.domain.tld pipedapi.domain.tld pipedproxy.domain.tld;` but my https://pipedapi.domain.tld/trending returns `{"message":"Invalid request sent."}` so it seems like there's something wrong here. I am experiencing this issue https://github.com/TeamPiped/Piped/issues/289 but my API_URL is publicly reachable (and returns the invalid request).

I did use the AIO script for nginx but I wonder if I should use the manual configuration instead. Problem is, since my reverse proxy is on a different machine, I can't use `proxy_pass http://unix:/var/run/ytproxy/http-proxy.sock;` for the proxy

**Comment by FireMasterK** [comment]
> So I am guessing `# For all 3 hostnames` means `server_name piped.domain.tld pipedapi.domain.tld pipedproxy.domain.tld;` but my https://pipedapi.domain.tld/trending returns `{"message":"Invalid request sent."}` so it seems like there's something wrong here. I am experiencing this issue #289 but my API_URL is publicly reachable (and returns the invalid request).

That's because `region` is a required parameter, for example https://pipedapi.kavin.rocks/trending?region=US works.

> I did use the AIO script for nginx but I wonder if I should use the manual configuration instead. Problem is, since my reverse proxy is on a different machine, I can't use `proxy_pass http://unix:/var/run/ytproxy/http-proxy.sock;` for the proxy. Or is it only for updating, not installing? I'm haven't seen anything else about updating the instance

I'd recommend using the AIO script, since it includes everything, it main purpose is to setup an instance with auto-updating capabilities.

> I just tried https://pipedapi.domain.told/trending?region=US and the json looks correct, but my subscriptions list still isn't updated automatically, I have to manually go to a channel to have it updated.

That happens when Google can't reach your server. Try having a look at pubsub's debug tool:
https://pubsubhubbub.appspot.com/subscribe
Callback URL example: https://pipedapi.kavin.rocks/webhooks/pubsub
Topic URL example: https://www.youtube.com/xml/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw
Example: https://pubsubhubbub.appspot.com/subscription-details?hub.callback=https%3A%2F%2Fpipedapi.kavin.rocks%2Fwebhooks%2Fpubsub&hub.topic=https%3A%2F%2Fwww.youtube.com%2Fxml%2Ffeeds%2Fvideos.xml%3Fchannel_id%3DUCXuqSBlHAE6Xw-yeJA0Tunw&hub.secret=

> Also https://pipedproxy.domain.told/?host=icanhazip.com returns `Non YouTube domains are not supported.` I'm not sure if it's what it should be

That's expected, it's a security feature to prevent it from being used as an open proxy.

**Comment by rderensy** [comment]
> it main purpose is to setup an instance with auto-updating capabilities.

So I don't need to update it? It's all done by itself?

> That happens when Google can't reach your server. Try having a look at pubsub's debug tool: 

Mine looks similar to yours, except my "Last item delivered" are `n/a`

**Comment by FireMasterK** [comment]
> So I don't need to update it? It's all done by itself?

Yes, that's correct!

> Mine looks similar to yours, except my "Last item delivered" are n/a

Is the subscription valid? Ie, it hasn't expired?

**Comment by rderensy** [comment]
> Is the subscription valid? Ie, it hasn't expired?

I guess not

````
Expiration time
Tue, 01 Mar 2022 12:05:36 +0000
````

**Comment by DracoMilesX** [comment]
Having some issues as well with this. My reverse proxy is on another machine.

I created a piped.domain.ltd pipedapi.domain.ltd and pipedproxy.domain.ltd as DNS records.

Trying to access piped.domain.ltd returns in the console `Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` and when I try to access pipedapi.domain.ltd directly it gives the error `backend fetch failed.` 

This is the config of the proxy file at the moment had to include the snippet in it otherwise swag wouldn't use it.

`server {
    listen 443 ssl;
    listen [::]:443 ssl;

    include /config/nginx/ssl.conf;
    server_name piped.* pipedapi.* pipedproxy.*; # For all 3 hostnames

    location / {
       proxy_pass <server up>;
       proxy_set_header Host $host;

	   add_header 'Access-Control-Allow-Origin' '*' always;
       proxy_hide_header Access-Control-Allow-Origin;
	   proxy_buffering on;
	   proxy_set_header Host $arg_host;
	   proxy_ssl_server_name on;
	   proxy_set_header X-Forwarded-For "";
	   proxy_set_header CF-Connecting-IP "";
	   proxy_hide_header "alt-svc";
	   sendfile on;
	   sendfile_max_chunk 512k;
	   tcp_nopush on;
	   aio threads=default;
	   aio_write on;
	   directio 2m;
	   proxy_hide_header Cache-Control;
	   proxy_hide_header etag;
	   proxy_http_version 1.1;
	   proxy_set_header Connection keep-alive;
	   proxy_max_temp_file_size 0;
	   access_log off;

    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    include /config/nginx/ssl.conf;
    server_name pipedproxy.*; # Change this depending on what domain you are using

    location ~ (/videoplayback|/api/v4/|/api/manifest/) {
       add_header Cache-Control private always;
       proxy_hide_header Access-Control-Allow-Origin;
	   
	   add_header 'Access-Control-Allow-Origin' '*' always;
       proxy_hide_header Access-Control-Allow-Origin;
	   proxy_buffering on;
	   proxy_set_header Host $arg_host;
	   proxy_ssl_server_name on;
	   proxy_set_header X-Forwarded-For "";
	   proxy_set_header CF-Connecting-IP "";
	   proxy_hide_header "alt-svc";
	   sendfile on;
	   sendfile_max_chunk 512k;
	   tcp_nopush on;
	   aio threads=default;
	   aio_write on;
	   directio 2m;
	   proxy_hide_header Cache-Control;
	   proxy_hide_header etag;
	   proxy_http_version 1.1;
	   proxy_set_header Connection keep-alive;
	   proxy_max_temp_file_size 0;
	   access_log off;

    }

    location / {
       add_header Cache-Control private always;
       add_header Cache-Control "public, max-age=604800";

	   add_header 'Access-Control-Allow-Origin' '*' always;
       proxy_hide_header Access-Control-Allow-Origin;
	   proxy_buffering on;
	   proxy_set_header Host $arg_host;
	   proxy_ssl_server_name on;
	   proxy_set_header X-Forwarded-For "";
	   proxy_set_header CF-Connecting-IP "";
	   proxy_hide_header "alt-svc";
	   sendfile on;
	   sendfile_max_chunk 512k;
	   tcp_nopush on;
	   aio threads=default;
	   aio_write on;
	   directio 2m;
	   proxy_hide_header Cache-Control;
	   proxy_hide_header etag;
	   proxy_http_version 1.1;
	   proxy_set_header Connection keep-alive;
	   proxy_max_temp_file_size 0;
	   access_log off;
    }
}`

**Comment by rderensy** [comment]
These conf files are only if you didn't use the AIO script and even if you didn't, they're meant to run with the docker, not on a dedicated reverse proxy. 

With a dedicated reverse proxy, this is enough:
```
server {
    listen 80;
    server_name piped.domain.ltd pipedapi.domain.ltd pipedproxy.domain.ltde;

    location / {
       proxy_pass http://<IP of backend server>:8080;
       proxy_set_header Host $host;
    }
}
```

**Comment by DracoMilesX** [comment]
While that works to access the frontend when I try to access pipedapi.domain.ltd it redirects me to the default webpage of my reverse proxy.

If i change `listen 80` to `listen 443` it gives me backend failed to fetch error when accessing pipedapi.
Having it on port 80 to listen instead of 443 gives me a bunch of those errors too for various .js files:

DevTools failed to load source map: Could not parse content for https://piped.domain.ltd/assets/TrendingPage.f4e677ea.js.map: Unexpected token < in JSON at position 0

This error stays as well: has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

A new error that I didnt saw yesterday with that config is;

`
Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (index.f92bc841.js:1:50611)
    at Proxy.fetchTrending (TrendingPage.f4e677ea.js:1:671)
    at Proxy.mounted (TrendingPage.f4e677ea.js:1:303)
    at Gt (vendor.e9844f41.js:1:12153)
    at ut (vendor.e9844f41.js:1:12232)
    at Array.Ca.t.__weh.t.__weh (vendor.e9844f41.js:1:21345)
    at ju (vendor.e9844f41.js:1:13670)
    at Wu (vendor.e9844f41.js:1:13896)
`

I wonder if its just my use case specific then or with dockerized reverse proxies. 

My webserver is on my NAS which runs docker and linuxserver/swag container for reverse proxy.
Piped will run on my proxmox server with a different port since 8080 is in use by something else.

**Comment by FireMasterK** [comment]
Do you pass the host header? That's extremely important, or else you will see nginx's default page.

**Comment by R8s6** [comment]
```
server {
    listen 80;
    server_name piped.domain.ltd pipedapi.domain.ltd pipedproxy.domain.ltde;

    location / {
       proxy_pass http://<IP of backend server>:8080;
       proxy_set_header Host $host;
    }
}
```

Where to add this part, is it `./Piped-Docker/config/ngnix.conf`?
