### ISSUE TITLE
store all already downloaded video parts to cache

### ISSUE THREAD

**Issue by e075e** [TeamPiped/Piped#907]
Hi,
piped does not completely store all video parts that has already been downloaded, for instance if you watching a music video and then you go backwards, the video will be downloaded again wasting bandwidth.

I have no idea how much cache is reserved for this in youtube or invidious, however no issue for music videos, maybe one of the type of video where you may want to listen again

Thanks

**Comment by lucamp** [comment]
### Firefox partial workaround
Install [LibRedirect](https://addons.mozilla.org/en-GB/firefox/addon/libredirect/)

- open LibRedirect setting
- go to YouTube page
- enable redirect to Piped
- Enable Custom Settings (will use cookies and localStorage)
- increase "Buffering Goal (in seconds)" to the desired amount (default 300 seconds)
- choose a single instance and not let it toggle all since some may not reliably work

Anything more than the buffer goal will not be kept, even if it's backward. But at least this works a little better and no issue for short videos

**Comment by Bnyro** [comment]
Same as https://github.com/TeamPiped/Piped/issues/2133
